In [13]:
import torch
x = torch.arange(4)
len(x)

4

In [14]:
A = torch.arange(20).reshape(5, 4)

In [15]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [16]:
a = torch.ones((2, 5, 4))

In [17]:
a.shape
a

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [18]:
a.sum(axis=1)

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [19]:
a.shape

torch.Size([2, 5, 4])

In [20]:
a.sum(axis=1).shape

torch.Size([2, 4])